services:
  - type: web
    name: cami-yonetim-sistemi
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: PORT
        value: "724"
      - key: TIDB_HOST
        sync: false
      - key: TIDB_PORT
        value: "4000"
      - key: TIDB_USER
        sync: false
      - key: TIDB_PASSWORD
        sync: false
      - key: TIDB_DATABASE
        value: "cami_sistemi"
